FOGL-2413 - Removed DataRetrievalError
foglamp/foglamp-south-game pull request #11
Opened 2019-02-22 09:42 UTC by amarendra-dianomic

2019-02-23 15:24 UTC, praveen-garg requested changes
Could you please give the old vs new logs if plugin is not able to read as expected?! or when reading wrapper dict is empty.

2019-02-23 15:24 UTC, praveen-garg commented on python/foglamp/plugins/south/game/game.py
> -        raise exceptions.DataRetrievalError(ex)
Also please remove its reference from docstring

2019-02-25 06:47 UTC, amarendra-dianomic commented on python/foglamp/plugins/south/game/game.py
> -        raise exceptions.DataRetrievalError(ex)
done

2019-02-25 10:32 UTC, praveen-garg approved these changes

2019-02-25 10:49 UTC, merged